server:
  port: 8888

spring:
  application:
    name: zkml-cloud-zuul-gateway   #为这个服务取名，非常重要！！！！！
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/,http://127.0.0.1:7003/eureka/
  instance:
    instance-id: zuul.com
    prefer-ip-address: true
